# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChessWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from ff import ExtendedQLabel

class Ui_Gameview(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1177, 1008)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gameoverbutton = QtWidgets.QPushButton(self.centralwidget)
        self.gameoverbutton.setGeometry(QtCore.QRect(0, 440, 141, 71))
        self.gameoverbutton.setObjectName("gameoverbutton")
        self.blackTimer = QtWidgets.QLabel(self.centralwidget)
        self.blackTimer.setGeometry(QtCore.QRect(30, 560, 101, 51))
        self.blackTimer.setObjectName("blackTimer")
        self.whiteTimer = QtWidgets.QLabel(self.centralwidget)
        self.whiteTimer.setGeometry(QtCore.QRect(30, 360, 101, 51))
        self.whiteTimer.setObjectName("whiteTimer")
        self.label01 = ExtendedQLabel(self.centralwidget)
        self.label01.setGeometry(QtCore.QRect(270, 10, 120, 120))
        self.label01.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label01.setFrameShape(QtWidgets.QFrame.Box)
        self.label01.setText("")
        self.label01.setPixmap(QtGui.QPixmap("WK.png"))
        self.label01.setAlignment(QtCore.Qt.AlignCenter)
        self.label01.setObjectName("label01")
        self.label02 = ExtendedQLabel(self.centralwidget)
        self.label02.setGeometry(QtCore.QRect(390, 10, 120, 120))
        self.label02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label02.setFrameShape(QtWidgets.QFrame.Box)
        self.label02.setText("")
        self.label02.setPixmap(QtGui.QPixmap("WB.png"))
        self.label02.setAlignment(QtCore.Qt.AlignCenter)
        self.label02.setObjectName("label02")
        self.label03 = ExtendedQLabel(self.centralwidget)
        self.label03.setGeometry(QtCore.QRect(510, 10, 120, 120))
        self.label03.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label03.setFrameShape(QtWidgets.QFrame.Box)
        self.label03.setText("")
        self.label03.setPixmap(QtGui.QPixmap("WKing.png"))
        self.label03.setAlignment(QtCore.Qt.AlignCenter)
        self.label03.setObjectName("label03")
        self.label04 = ExtendedQLabel(self.centralwidget)
        self.label04.setGeometry(QtCore.QRect(630, 10, 120, 120))
        self.label04.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label04.setFrameShape(QtWidgets.QFrame.Box)
        self.label04.setText("")
        self.label04.setPixmap(QtGui.QPixmap("WQ.png"))
        self.label04.setAlignment(QtCore.Qt.AlignCenter)
        self.label04.setObjectName("label04")
        self.label05 = ExtendedQLabel(self.centralwidget)
        self.label05.setGeometry(QtCore.QRect(750, 10, 120, 120))
        self.label05.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label05.setFrameShape(QtWidgets.QFrame.Box)
        self.label05.setText("")
        self.label05.setPixmap(QtGui.QPixmap("WB.png"))
        self.label05.setAlignment(QtCore.Qt.AlignCenter)
        self.label05.setObjectName("label05")
        self.label06 = ExtendedQLabel(self.centralwidget)
        self.label06.setGeometry(QtCore.QRect(870, 10, 120, 120))
        self.label06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label06.setFrameShape(QtWidgets.QFrame.Box)
        self.label06.setText("")
        self.label06.setPixmap(QtGui.QPixmap("WK.png"))
        self.label06.setAlignment(QtCore.Qt.AlignCenter)
        self.label06.setObjectName("label06")
        self.label00 = ExtendedQLabel(self.centralwidget)
        self.label00.setGeometry(QtCore.QRect(150, 10, 120, 120))
        self.label00.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label00.setFrameShape(QtWidgets.QFrame.Box)
        self.label00.setText("")
        self.label00.setPixmap(QtGui.QPixmap("WR.png"))
        self.label00.setAlignment(QtCore.Qt.AlignCenter)
        self.label00.setObjectName("label00")
        self.label07 = ExtendedQLabel(self.centralwidget)
        self.label07.setGeometry(QtCore.QRect(990, 10, 120, 120))
        self.label07.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label07.setFrameShape(QtWidgets.QFrame.Box)
        self.label07.setText("")
        self.label07.setPixmap(QtGui.QPixmap("WR.png"))
        self.label07.setAlignment(QtCore.Qt.AlignCenter)
        self.label07.setObjectName("label07")
        self.label10 = ExtendedQLabel(self.centralwidget)
        self.label10.setGeometry(QtCore.QRect(150, 130, 120, 120))
        self.label10.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label10.setFrameShape(QtWidgets.QFrame.Box)
        self.label10.setText("")
        self.label10.setPixmap(QtGui.QPixmap("WP.png"))
        self.label10.setAlignment(QtCore.Qt.AlignCenter)
        self.label10.setObjectName("label10")
        self.label15 = ExtendedQLabel(self.centralwidget)
        self.label15.setGeometry(QtCore.QRect(750, 130, 120, 120))
        self.label15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label15.setFrameShape(QtWidgets.QFrame.Box)
        self.label15.setText("")
        self.label15.setPixmap(QtGui.QPixmap("WP.png"))
        self.label15.setAlignment(QtCore.Qt.AlignCenter)
        self.label15.setObjectName("label15")
        self.label12 = ExtendedQLabel(self.centralwidget)
        self.label12.setGeometry(QtCore.QRect(390, 130, 120, 120))
        self.label12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label12.setFrameShape(QtWidgets.QFrame.Box)
        self.label12.setText("")
        self.label12.setPixmap(QtGui.QPixmap("WP.png"))
        self.label12.setAlignment(QtCore.Qt.AlignCenter)
        self.label12.setObjectName("label12")
        self.label17 = ExtendedQLabel(self.centralwidget)
        self.label17.setGeometry(QtCore.QRect(990, 130, 120, 120))
        self.label17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label17.setFrameShape(QtWidgets.QFrame.Box)
        self.label17.setText("")
        self.label17.setPixmap(QtGui.QPixmap("WP.png"))
        self.label17.setAlignment(QtCore.Qt.AlignCenter)
        self.label17.setObjectName("label17")
        self.label13 = ExtendedQLabel(self.centralwidget)
        self.label13.setGeometry(QtCore.QRect(510, 130, 120, 120))
        self.label13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label13.setFrameShape(QtWidgets.QFrame.Box)
        self.label13.setText("")
        self.label13.setPixmap(QtGui.QPixmap("WP.png"))
        self.label13.setAlignment(QtCore.Qt.AlignCenter)
        self.label13.setObjectName("label13")
        self.label11 = ExtendedQLabel(self.centralwidget)
        self.label11.setGeometry(QtCore.QRect(270, 130, 120, 120))
        self.label11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label11.setFrameShape(QtWidgets.QFrame.Box)
        self.label11.setText("")
        self.label11.setPixmap(QtGui.QPixmap("WP.png"))
        self.label11.setAlignment(QtCore.Qt.AlignCenter)
        self.label11.setObjectName("label11")
        self.label16 = ExtendedQLabel(self.centralwidget)
        self.label16.setGeometry(QtCore.QRect(870, 130, 120, 120))
        self.label16.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label16.setFrameShape(QtWidgets.QFrame.Box)
        self.label16.setText("")
        self.label16.setPixmap(QtGui.QPixmap("WP.png"))
        self.label16.setAlignment(QtCore.Qt.AlignCenter)
        self.label16.setObjectName("label16")
        self.label14 = ExtendedQLabel(self.centralwidget)
        self.label14.setGeometry(QtCore.QRect(630, 130, 120, 120))
        self.label14.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label14.setFrameShape(QtWidgets.QFrame.Box)
        self.label14.setText("")
        self.label14.setPixmap(QtGui.QPixmap("WP.png"))
        self.label14.setAlignment(QtCore.Qt.AlignCenter)
        self.label14.setObjectName("label14")
        self.label20 = ExtendedQLabel(self.centralwidget)
        self.label20.setGeometry(QtCore.QRect(150, 250, 120, 120))
        self.label20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label20.setFrameShape(QtWidgets.QFrame.Box)
        self.label20.setText("")
        self.label20.setObjectName("label20")
        self.label25 = ExtendedQLabel(self.centralwidget)
        self.label25.setGeometry(QtCore.QRect(750, 250, 120, 120))
        self.label25.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label25.setFrameShape(QtWidgets.QFrame.Box)
        self.label25.setText("")
        self.label25.setObjectName("label25")
        self.label22 = ExtendedQLabel(self.centralwidget)
        self.label22.setGeometry(QtCore.QRect(390, 250, 120, 120))
        self.label22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label22.setFrameShape(QtWidgets.QFrame.Box)
        self.label22.setText("")
        self.label22.setObjectName("label22")
        self.label27 = ExtendedQLabel(self.centralwidget)
        self.label27.setGeometry(QtCore.QRect(990, 250, 120, 120))
        self.label27.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label27.setFrameShape(QtWidgets.QFrame.Box)
        self.label27.setText("")
        self.label27.setObjectName("label27")
        self.label23 = ExtendedQLabel(self.centralwidget)
        self.label23.setGeometry(QtCore.QRect(510, 250, 120, 120))
        self.label23.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label23.setFrameShape(QtWidgets.QFrame.Box)
        self.label23.setText("")
        self.label23.setObjectName("label23")
        self.label21 = ExtendedQLabel(self.centralwidget)
        self.label21.setGeometry(QtCore.QRect(270, 250, 120, 120))
        self.label21.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label21.setFrameShape(QtWidgets.QFrame.Box)
        self.label21.setText("")
        self.label21.setObjectName("label21")
        self.label26 = ExtendedQLabel(self.centralwidget)
        self.label26.setGeometry(QtCore.QRect(870, 250, 120, 120))
        self.label26.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label26.setFrameShape(QtWidgets.QFrame.Box)
        self.label26.setText("")
        self.label26.setObjectName("label26")
        self.label24 = ExtendedQLabel(self.centralwidget)
        self.label24.setGeometry(QtCore.QRect(630, 250, 120, 120))
        self.label24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label24.setFrameShape(QtWidgets.QFrame.Box)
        self.label24.setText("")
        self.label24.setObjectName("label24")
        self.label30 = ExtendedQLabel(self.centralwidget)
        self.label30.setGeometry(QtCore.QRect(150, 370, 120, 120))
        self.label30.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label30.setFrameShape(QtWidgets.QFrame.Box)
        self.label30.setText("")
        self.label30.setObjectName("label30")
        self.label35 = ExtendedQLabel(self.centralwidget)
        self.label35.setGeometry(QtCore.QRect(750, 370, 120, 120))
        self.label35.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label35.setFrameShape(QtWidgets.QFrame.Box)
        self.label35.setText("")
        self.label35.setObjectName("label35")
        self.label32 = ExtendedQLabel(self.centralwidget)
        self.label32.setGeometry(QtCore.QRect(390, 370, 120, 120))
        self.label32.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label32.setFrameShape(QtWidgets.QFrame.Box)
        self.label32.setText("")
        self.label32.setObjectName("label32")
        self.label37 = ExtendedQLabel(self.centralwidget)
        self.label37.setGeometry(QtCore.QRect(990, 370, 120, 120))
        self.label37.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label37.setFrameShape(QtWidgets.QFrame.Box)
        self.label37.setText("")
        self.label37.setObjectName("label37")
        self.label33 = ExtendedQLabel(self.centralwidget)
        self.label33.setGeometry(QtCore.QRect(510, 370, 120, 120))
        self.label33.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label33.setFrameShape(QtWidgets.QFrame.Box)
        self.label33.setText("")
        self.label33.setObjectName("label33")
        self.label31 = ExtendedQLabel(self.centralwidget)
        self.label31.setGeometry(QtCore.QRect(270, 370, 120, 120))
        self.label31.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label31.setFrameShape(QtWidgets.QFrame.Box)
        self.label31.setText("")
        self.label31.setObjectName("label31")
        self.label36 = ExtendedQLabel(self.centralwidget)
        self.label36.setGeometry(QtCore.QRect(870, 370, 120, 120))
        self.label36.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label36.setFrameShape(QtWidgets.QFrame.Box)
        self.label36.setText("")
        self.label36.setObjectName("label36")
        self.label34 = ExtendedQLabel(self.centralwidget)
        self.label34.setGeometry(QtCore.QRect(630, 370, 120, 120))
        self.label34.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label34.setFrameShape(QtWidgets.QFrame.Box)
        self.label34.setText("")
        self.label34.setObjectName("label34")
        self.label40 = ExtendedQLabel(self.centralwidget)
        self.label40.setGeometry(QtCore.QRect(150, 490, 120, 120))
        self.label40.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label40.setFrameShape(QtWidgets.QFrame.Box)
        self.label40.setText("")
        self.label40.setObjectName("label40")
        self.label45 = ExtendedQLabel(self.centralwidget)
        self.label45.setGeometry(QtCore.QRect(750, 490, 120, 120))
        self.label45.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label45.setFrameShape(QtWidgets.QFrame.Box)
        self.label45.setText("")
        self.label45.setObjectName("label45")
        self.label42 = ExtendedQLabel(self.centralwidget)
        self.label42.setGeometry(QtCore.QRect(390, 490, 120, 120))
        self.label42.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label42.setFrameShape(QtWidgets.QFrame.Box)
        self.label42.setText("")
        self.label42.setObjectName("label42")
        self.label47 = ExtendedQLabel(self.centralwidget)
        self.label47.setGeometry(QtCore.QRect(990, 490, 120, 120))
        self.label47.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label47.setFrameShape(QtWidgets.QFrame.Box)
        self.label47.setText("")
        self.label47.setObjectName("label47")
        self.label43 = ExtendedQLabel(self.centralwidget)
        self.label43.setGeometry(QtCore.QRect(510, 490, 120, 120))
        self.label43.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label43.setFrameShape(QtWidgets.QFrame.Box)
        self.label43.setText("")
        self.label43.setObjectName("label43")
        self.label41 = ExtendedQLabel(self.centralwidget)
        self.label41.setGeometry(QtCore.QRect(270, 490, 120, 120))
        self.label41.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label41.setFrameShape(QtWidgets.QFrame.Box)
        self.label41.setText("")
        self.label41.setObjectName("label41")
        self.label46 = ExtendedQLabel(self.centralwidget)
        self.label46.setGeometry(QtCore.QRect(870, 490, 120, 120))
        self.label46.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label46.setFrameShape(QtWidgets.QFrame.Box)
        self.label46.setText("")
        self.label46.setObjectName("label46")
        self.label44 = ExtendedQLabel(self.centralwidget)
        self.label44.setGeometry(QtCore.QRect(630, 490, 120, 120))
        self.label44.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label44.setFrameShape(QtWidgets.QFrame.Box)
        self.label44.setText("")
        self.label44.setObjectName("label44")
        self.label50 = ExtendedQLabel(self.centralwidget)
        self.label50.setGeometry(QtCore.QRect(150, 610, 120, 120))
        self.label50.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label50.setFrameShape(QtWidgets.QFrame.Box)
        self.label50.setText("")
        self.label50.setObjectName("label50")
        self.label55 = ExtendedQLabel(self.centralwidget)
        self.label55.setGeometry(QtCore.QRect(750, 610, 120, 120))
        self.label55.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label55.setFrameShape(QtWidgets.QFrame.Box)
        self.label55.setText("")
        self.label55.setObjectName("label55")
        self.label52 = ExtendedQLabel(self.centralwidget)
        self.label52.setGeometry(QtCore.QRect(390, 610, 120, 120))
        self.label52.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label52.setFrameShape(QtWidgets.QFrame.Box)
        self.label52.setText("")
        self.label52.setObjectName("label52")
        self.label57 = ExtendedQLabel(self.centralwidget)
        self.label57.setGeometry(QtCore.QRect(990, 610, 120, 120))
        self.label57.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label57.setFrameShape(QtWidgets.QFrame.Box)
        self.label57.setText("")
        self.label57.setObjectName("label57")
        self.label53 = ExtendedQLabel(self.centralwidget)
        self.label53.setGeometry(QtCore.QRect(510, 610, 120, 120))
        self.label53.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label53.setFrameShape(QtWidgets.QFrame.Box)
        self.label53.setText("")
        self.label53.setObjectName("label53")
        self.label51 = ExtendedQLabel(self.centralwidget)
        self.label51.setGeometry(QtCore.QRect(270, 610, 120, 120))
        self.label51.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label51.setFrameShape(QtWidgets.QFrame.Box)
        self.label51.setText("")
        self.label51.setObjectName("label51")
        self.label56 = ExtendedQLabel(self.centralwidget)
        self.label56.setGeometry(QtCore.QRect(870, 610, 120, 120))
        self.label56.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label56.setFrameShape(QtWidgets.QFrame.Box)
        self.label56.setText("")
        self.label56.setObjectName("label56")
        self.label54 = ExtendedQLabel(self.centralwidget)
        self.label54.setGeometry(QtCore.QRect(630, 610, 120, 120))
        self.label54.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label54.setFrameShape(QtWidgets.QFrame.Box)
        self.label54.setText("")
        self.label54.setObjectName("label54")
        self.label60 = ExtendedQLabel(self.centralwidget)
        self.label60.setGeometry(QtCore.QRect(150, 730, 120, 120))
        self.label60.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label60.setFrameShape(QtWidgets.QFrame.Box)
        self.label60.setText("")
        self.label60.setPixmap(QtGui.QPixmap("BP1.png"))
        self.label60.setAlignment(QtCore.Qt.AlignCenter)
        self.label60.setObjectName("label60")
        self.label65 = ExtendedQLabel(self.centralwidget)
        self.label65.setGeometry(QtCore.QRect(750, 730, 120, 120))
        self.label65.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label65.setFrameShape(QtWidgets.QFrame.Box)
        self.label65.setText("")
        self.label65.setPixmap(QtGui.QPixmap("BP1.png"))
        self.label65.setAlignment(QtCore.Qt.AlignCenter)
        self.label65.setObjectName("label65")
        self.label62 = ExtendedQLabel(self.centralwidget)
        self.label62.setGeometry(QtCore.QRect(390, 730, 120, 120))
        self.label62.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label62.setFrameShape(QtWidgets.QFrame.Box)
        self.label62.setText("")
        self.label62.setPixmap(QtGui.QPixmap("BP1.png"))
        self.label62.setAlignment(QtCore.Qt.AlignCenter)
        self.label62.setObjectName("label62")
        self.label67 = ExtendedQLabel(self.centralwidget)
        self.label67.setGeometry(QtCore.QRect(990, 730, 120, 120))
        self.label67.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label67.setFrameShape(QtWidgets.QFrame.Box)
        self.label67.setText("")
        self.label67.setPixmap(QtGui.QPixmap("BP1.png"))
        self.label67.setScaledContents(False)
        self.label67.setAlignment(QtCore.Qt.AlignCenter)
        self.label67.setObjectName("label67")
        self.label63 = ExtendedQLabel(self.centralwidget)
        self.label63.setGeometry(QtCore.QRect(510, 730, 120, 120))
        self.label63.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label63.setFrameShape(QtWidgets.QFrame.Box)
        self.label63.setText("")
        self.label63.setPixmap(QtGui.QPixmap("BP1.png"))
        self.label63.setAlignment(QtCore.Qt.AlignCenter)
        self.label63.setObjectName("label63")
        self.label61 = ExtendedQLabel(self.centralwidget)
        self.label61.setGeometry(QtCore.QRect(270, 730, 120, 120))
        self.label61.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label61.setFrameShape(QtWidgets.QFrame.Box)
        self.label61.setText("")
        self.label61.setPixmap(QtGui.QPixmap("BP1.png"))
        self.label61.setAlignment(QtCore.Qt.AlignCenter)
        self.label61.setObjectName("label61")
        self.label66 = ExtendedQLabel(self.centralwidget)
        self.label66.setGeometry(QtCore.QRect(870, 730, 120, 120))
        self.label66.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label66.setFrameShape(QtWidgets.QFrame.Box)
        self.label66.setText("")
        self.label66.setPixmap(QtGui.QPixmap("BP1.png"))
        self.label66.setAlignment(QtCore.Qt.AlignCenter)
        self.label66.setObjectName("label66")
        self.label64 = ExtendedQLabel(self.centralwidget)
        self.label64.setGeometry(QtCore.QRect(630, 730, 120, 120))
        self.label64.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label64.setFrameShape(QtWidgets.QFrame.Box)
        self.label64.setText("")
        self.label64.setPixmap(QtGui.QPixmap("BP1.png"))
        self.label64.setAlignment(QtCore.Qt.AlignCenter)
        self.label64.setObjectName("label64")
        self.label70 = ExtendedQLabel(self.centralwidget)
        self.label70.setGeometry(QtCore.QRect(150, 850, 120, 120))
        self.label70.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label70.setFrameShape(QtWidgets.QFrame.Box)
        self.label70.setText("")
        self.label70.setPixmap(QtGui.QPixmap("BR.png"))
        self.label70.setAlignment(QtCore.Qt.AlignCenter)
        self.label70.setObjectName("label70")
        self.label75 = ExtendedQLabel(self.centralwidget)
        self.label75.setGeometry(QtCore.QRect(750, 850, 120, 120))
        self.label75.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label75.setFrameShape(QtWidgets.QFrame.Box)
        self.label75.setText("")
        self.label75.setPixmap(QtGui.QPixmap("BB.png"))
        self.label75.setAlignment(QtCore.Qt.AlignCenter)
        self.label75.setObjectName("label75")
        self.label72 = ExtendedQLabel(self.centralwidget)
        self.label72.setGeometry(QtCore.QRect(390, 850, 120, 120))
        self.label72.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label72.setFrameShape(QtWidgets.QFrame.Box)
        self.label72.setText("")
        self.label72.setPixmap(QtGui.QPixmap("BB.png"))
        self.label72.setAlignment(QtCore.Qt.AlignCenter)
        self.label72.setObjectName("label72")
        self.label77 = ExtendedQLabel(self.centralwidget)
        self.label77.setGeometry(QtCore.QRect(990, 850, 120, 120))
        self.label77.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label77.setFrameShape(QtWidgets.QFrame.Box)
        self.label77.setText("")
        self.label77.setPixmap(QtGui.QPixmap("BR.png"))
        self.label77.setAlignment(QtCore.Qt.AlignCenter)
        self.label77.setObjectName("label77")
        self.label73 = ExtendedQLabel(self.centralwidget)
        self.label73.setGeometry(QtCore.QRect(510, 850, 120, 120))
        self.label73.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label73.setFrameShape(QtWidgets.QFrame.Box)
        self.label73.setText("")
        self.label73.setPixmap(QtGui.QPixmap("BKing.png"))
        self.label73.setAlignment(QtCore.Qt.AlignCenter)
        self.label73.setObjectName("label73")
        self.label71 = ExtendedQLabel(self.centralwidget)
        self.label71.setGeometry(QtCore.QRect(270, 850, 120, 120))
        self.label71.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label71.setFrameShape(QtWidgets.QFrame.Box)
        self.label71.setText("")
        self.label71.setPixmap(QtGui.QPixmap("BK.png"))
        self.label71.setAlignment(QtCore.Qt.AlignCenter)
        self.label71.setObjectName("label71")
        self.label76 = ExtendedQLabel(self.centralwidget)
        self.label76.setGeometry(QtCore.QRect(870, 850, 120, 120))
        self.label76.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label76.setFrameShape(QtWidgets.QFrame.Box)
        self.label76.setText("")
        self.label76.setPixmap(QtGui.QPixmap("BK.png"))
        self.label76.setAlignment(QtCore.Qt.AlignCenter)
        self.label76.setObjectName("label76")
        self.label74 = ExtendedQLabel(self.centralwidget)
        self.label74.setGeometry(QtCore.QRect(630, 850, 120, 120))
        self.label74.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label74.setFrameShape(QtWidgets.QFrame.Box)
        self.label74.setText("")
        self.label74.setPixmap(QtGui.QPixmap("BQ.png"))
        self.label74.setAlignment(QtCore.Qt.AlignCenter)
        self.label74.setObjectName("label74")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gameoverbutton.setText(_translate("MainWindow", "Game Over"))
        self.blackTimer.setText(_translate("MainWindow", "TextLabel"))
        self.whiteTimer.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Gameview()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
